red-flag-schematic: "redflag.schem"
green-flag-schematic: "greenflag.schem"
blue-flag-schematic: "blueflag.schem"
yellow-flag-schematic: "yellowflag.schem"
white-flag-schematic: "whiteflag.schem"

capture-distance: 10.0
capture-multiplier: 1.0
# timer is in ticks (there are 20 ticks per second)
capture-update-timer: 20
warning-message-timer: 60

game-world: "world"
lobby-world: "world"

# game timer is in minutes
game-timer: 30

# middle tile is in minutes
middle-tile-timer: 20
