red-flag-schematic: "redflag.schem"
green-flag-schematic: "greenflag.schem"
blue-flag-schematic: "blueflag.schem"
yellow-flag-schematic: "yellowflag.schem"
white-flag-schematic: "whiteflag.schem"

capture-distance: 10.0
capture-multiplier: 1.0
# timer is in ticks (there are 20 ticks per second)
capture-update-timer: 20
